Diagnostic_Laboratory/Diagnostic_Laboratory/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import home
from .views import DevelopersView


urlpatterns = [


    # Superuser
    path('admin/', admin.site.urls),

    # Home
    path('', home, name='home'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (diagnostic)
    path('', include('diagnostic.urls', namespace='diagnostic')),

    # App3 (medicine_tests)
    path('', include('medicine_tests.urls', namespace='medicine_tests')),

    # App3 (report_processing)
    path('', include('report_processing.urls', namespace='report_processing')),

    # Allauth (built-in)
    path('accounts/', include('allauth.urls')),

    # Developers
    path('developers/', DevelopersView.as_view(), name='developers'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Diagnostic_Laboratory/diagnostic/urls.py
from django.urls import path

from .views import (

    search_paginator,

    admin_login,
    admin_logout,
    admin_dashboard,

    staff_login,
    staff_logout,
    staff_dashboard,

    center_details,

)


app_name = 'diagnostic'

urlpatterns = [

    path('all-centers/', search_paginator, name='all-centers'),

    path('admin-login/', admin_login, name='admin-login'),
    path('admin-logout/', admin_logout, name='admin-logout'),
    path('admin-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),

    path('staff-login/', staff_login, name='staff-login'),
    path('staff-logout/', staff_logout, name='staff-logout'),
    path('staff-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('staff-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),

    path('center-details/<int:id>/', center_details, name='center-details'),


]

Diagnostic_Laboratory/medicine_tests/urls.py
from django.urls import path

from .views import (

    all_tests,
    test_details,

    test_order,
    order_details_info,

    test_categories,
    categorise_tests,

    staff_approved,
    staff_rejected,

    add_test_by_admin,
    add_category_by_admin,
    filtered_categories_by_admin,
    filtered_categories_for_staff,

    delete_test,
    edit_test,

    edit_category,
    delete_category,

    all_tests_list_for_staff,
    added_tests_list_for_staff_admin,

    confirm_payment_message,

    came_for_test,

    total_test_count_center_staff,

)


app_name = 'medicine_tests'


urlpatterns = [

    path('all-medicine_tests/', all_tests, name='all-medicine_tests'),

    path('categories/', test_categories, name='categories'),

    path('categorise-medicine_tests/<int:id>/', categorise_tests, name='categorise-medicine_tests'),

    path('test-details/<int:id>/', test_details, name='test-details'),

    path('order/<int:id>/', test_order, name='order'),

    path('order-details/<int:id>/', order_details_info, name='order-details'),

    path('staff-approved/<int:id>/<username>/', staff_approved, name='staff-approved'),

    path('staff-rejected/<int:id>/<username>/', staff_rejected, name='staff-rejected'),

    path('add-test/<username>/', add_test_by_admin, name='add-test'),

    path('add-category/<username>/', add_category_by_admin, name='add-category'),

    path('filtered-categories-by-admin/<username>/', filtered_categories_by_admin, name='filtered-categories-by-admin'),

    path('filtered-categories-for-staff/<username>/', filtered_categories_for_staff, name='filtered-categories-for-staff'),

    path('all-medicine_tests-list-staff/<username>/', all_tests_list_for_staff, name='all-medicine_tests-list-staff'),

    path('added-medicine_tests-list-staff-admin/<username>/', added_tests_list_for_staff_admin, name='added-medicine_tests-list-staff-admin'),

    path('delete-test/<int:id>/<username>/', delete_test, name='delete_test'),

    path('delete-category/<int:id>/<username>/', delete_category, name='delete-category'),

    path('edit-test/<int:id>/<username>/', edit_test, name='edit-test'),

    path('edit-category/<int:id>/<username>/', edit_category, name='edit-category'),

    path('confirm-payment-message/<int:id>/', confirm_payment_message, name='confirm-payment-message'),

    path('staff-confirm-payment-message/<int:id>/<username>/', confirm_payment_message, name='staff-confirm-payment-message'),

    path('came-for-test/<int:id>/<username>/', came_for_test, name='came-for-test'),

    path('total-test-count-center-staff/<int:id>/', total_test_count_center_staff, name='total-test-count-center-staff'),


]

Diagnostic_Laboratory/medicine_tests/forms.py
from django import forms
from django.forms import TextInput, Select, SelectDateWidget, TimeInput, DateInput

from .models import TestOrder, Test, TestCategory


class TestOrderForm(forms.ModelForm):
    class Meta:
        model = TestOrder

        fields = '__all__'

        exclude = ['client_info', 'test_info', 'order_created_at', 'staff_check', 'admin_approve',
                   'accepted', 'validation', 'order_confirmed', 'came_for_test']

        widgets = {
            'client_info': Select(attrs={'class': 'form-control'}),
            'contact_no': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'test_info': Select(attrs={'class': 'form-control'}),
            'payment_type': Select(attrs={'class': 'custom-select'}),
            'payment_method': Select(attrs={'class': 'custom-select'}),
            'booked_time_slot': Select(attrs={'class': 'custom-select'}),
            'booked_date': SelectDateWidget(attrs={'class': 'custom-select'})
        }


class TestAddForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['test_name', 'image', 'category',
                  'discount', 'price', 'active_status']
        exclude = ['center', ]

        widgets = {
            'test_name': TextInput(attrs={'class': 'form-control'}),
            'category': Select(attrs={'class': 'custom-select'}),
            # 'center': Select(attrs={'class': 'form-control'}),
            'discount': TextInput(attrs={'class': 'form-control'}),
            'price': TextInput(attrs={'class': 'form-control'}),
            'active_status': Select(attrs={'class': 'form-control'}),
        }


class CategoryAddForm(forms.ModelForm):
    class Meta:
        model = TestCategory

        fields = ['category_name']

        exclude = ['center', ]

        widgets = {'category_name': TextInput(attrs={'class': 'form-control'})}

Diagnostic_Laboratory/medicine_tests/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages

from custom_users.models import Profile
from diagnostic.models import DiagnosticAdmin, DiagnosticStaff, DiagnosticCenter

from .models import Test, TestCategory, TestOrder
from .forms import TestOrderForm, TestAddForm, CategoryAddForm


########################################################################################


def all_tests(request, template_name='medicine_tests/all_tests.html'):
    all_test_list = Test.objects.all().order_by('-id')

    query = request.GET.get('q')

    if query:
        all_test_list = all_test_list.filter(Q(test_name__icontains=query)).distinct()

    paginator = Paginator(all_test_list, 12)
    page = request.GET.get('page')
    all_test_paginator_data = paginator.get_page(page)

    context = {
        'all_test_list': all_test_list,
        'all_test_paginator_data': all_test_paginator_data,
    }

    return render(request, template_name, context)

########################################################################################


def test_categories(request, template_name='medicine_tests/categories.html'):
    categories = TestCategory.objects.all().order_by('-id')

    context = {'categories': categories}

    return render(request, template_name, context)

########################################################################################


def categorise_tests(request, id=None):
    filtered_tests = Test.objects.filter(category__id=id)

    template = 'medicine_tests/categorise_tests.html'
    context = {'filtered_tests': filtered_tests}

    return render(request, template, context)

########################################################################################


def test_details(request, id=id):
    single_test_details = Test.objects.get(id=id)

    template = 'medicine_tests/test_details.html'
    context = {'single_test_details': single_test_details}

    return render(request, template, context)

########################################################################################


@login_required
def test_order(request, id=None):
    try:
        current_profile = Profile.objects.get(user=request.user)
        email = current_profile.user.email
        contact_no = current_profile.contact_no
        address = current_profile.address
        initial_data = {
            'email':email,
            'contact_no': contact_no,
            'address':address
        }
    except:
        return redirect('account_login')
    if request.method == 'POST':
        test_order_form = TestOrderForm(request.POST)
        if test_order_form.is_valid():
            order = test_order_form.save(commit=False)
            order.client_info = Profile.objects.get(user=request.user)
            order.test_info = Test.objects.get(id=id)
            order.save()
            return redirect('medicine_tests:order-details', id=order.id)
    context = {
        'test_order_form': TestOrderForm(initial=initial_data),
        'test_id': id,
    }
    template = 'medicine_tests/order.html'
    return render(request, template, context)

########################################################################################


def order_details_info(request, id=None):
    order_details = TestOrder.objects.get(id=id)

    total_price = int(order_details.test_info.price - order_details.test_info.discount)

    template = 'medicine_tests/order_details.html'

    context = {
        'order_details': order_details,
        'total_price': total_price,
    }

    return render(request, template, context)

########################################################################################


def staff_approved(request, id=None, username=None):
    staff_order_detail = TestOrder.objects.get(id=id)
    staff_order_detail.accepted = True
    staff_order_detail.staff_check = True
    staff_order_detail.save()

    return redirect('diagnostic:staff-dashboard', username=username)

########################################################################################


def staff_rejected(request, id=None, username=None):
    staff_order_detail = TestOrder.objects.get(id=id)
    staff_order_detail.accepted = False
    staff_order_detail.staff_check = True
    staff_order_detail.save()

    return redirect('diagnostic:staff-dashboard', username=username)


########################################################################################


def add_test_by_admin(request, username=None):
    if request.method == 'POST':
        test_add_form = TestAddForm(request.POST)

        if test_add_form.is_valid():
            add_test = test_add_form.save(commit=False)

            admin = DiagnosticAdmin.objects.get(username=username)
            add_test.center = DiagnosticCenter.objects.get(id=admin.center.id)

            add_test.save()

            return redirect('medicine_tests:added-medicine_tests-list-staff-admin', username)

    else:
        test_add_form = TestAddForm()

    template = 'medicine_tests/add_test.html'
    context = {'test_add_form': test_add_form}

    return render(request, template, context)

########################################################################################


def add_category_by_admin(request, username=None):
    if request.method == 'POST':
        category_add_form = CategoryAddForm(request.POST)

        if category_add_form.is_valid():
            add_category = category_add_form.save(commit=False)

            admin = DiagnosticAdmin.objects.get(username=username)
            add_category.center = DiagnosticCenter.objects.get(id=admin.center.id)

            add_category.save()

            return redirect('medicine_tests:filtered-categories-by-admin', username)

    else:
        category_add_form = CategoryAddForm()

    template = 'medicine_tests/add_category.html'
    context = {'category_add_form': category_add_form}

    return render(request, template, context)

########################################################################################


def edit_category(request, id=None, username=None):
    category_query = TestCategory.objects.get(id=id)
    edit_form = CategoryAddForm(request.POST or None, instance=category_query)

    if request.method == 'POST':
        if edit_form.is_valid():
            edited = edit_form.save(commit=False)

            admin = DiagnosticAdmin.objects.get(username=username)
            edited.center = DiagnosticCenter.objects.get(id=admin.center.id)

            edited.save()

            return redirect('medicine_tests:filtered-categories-by-admin', username)

    template = 'medicine_tests/edit_category.html'

    context = {'edit_form': edit_form}

    return render(request, template, context)

########################################################################################


def delete_category(request, id=None, username=None):
    category_object = TestCategory.objects.get(id=id)
    admin = DiagnosticAdmin.objects.get(username=username)

    category_object.center = DiagnosticCenter.objects.get(id=admin.center.id)

    if category_object.center is not None:
        category_object.delete()

    return redirect('medicine_tests:filtered-categories-by-admin', username)

########################################################################################


def filtered_categories_by_admin(request, username=None):
    admin = DiagnosticAdmin.objects.get(username=username)

    added_categories_admin = TestCategory.objects.filter(center__center_admins=admin)

    template = 'medicine_tests/filtered_categories_admin.html'

    context = {
        'added_categories_admin': added_categories_admin,
        'admin': admin,

    }

    return render(request, template, context)

########################################################################################


def filtered_categories_for_staff(request, username=None):
    staff = DiagnosticStaff.objects.get(username=username)

    categories_staff = TestCategory.objects.filter(center__center_staffs=staff)

    template = 'medicine_tests/filtered_categories_staff.html'

    context = {
        'categories_staff': categories_staff,
        'staff': staff,
    }

    return render(request, template, context)

########################################################################################


def all_tests_list_for_staff(request, username):
    staff = DiagnosticStaff.objects.get(username=username)

    staff_filtered_tests = Test.objects.filter(center__center_staffs=staff)

    # All added medicine_tests Paginator
    paginator = Paginator(staff_filtered_tests, 20)
    page = request.GET.get('page')
    all_added_tests_paginator_data = paginator.get_page(page)

    template = 'medicine_tests/all_tests_list_for_staff.html'
    context = {
        'all_added_tests': all_added_tests_paginator_data,
        'staff': staff,
    }

    return render(request, template, context)

########################################################################################


def added_tests_list_for_staff_admin(request, username=None):

    admin = DiagnosticAdmin.objects.get(username=username)

    added_tests = Test.objects.filter(center__center_admins=admin)


    # All added medicine_tests Paginator
    paginator = Paginator(added_tests, 20)
    page = request.GET.get('page')
    added_tests_paginator_data = paginator.get_page(page)

    template = 'medicine_tests/added_tests_list_for_staff_admin.html'

    context = {
        'all_added_tests': added_tests_paginator_data,
        'admin': admin,
            }

    return render(request, template, context)

########################################################################################


def delete_test(request, id=None, username=None):
    test_object = Test.objects.get(id=id)

Diagnostic_Laboratory/templates/medicine_tests/added_tests_list_for_staff_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Added Test-Admin | Диагностика</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link href="{% static  'css/plugin.css' %}" rel="stylesheet">
</head>

<body class="common-">
    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-white"
                href="{% url 'diagnostic:admin-dashboard' admin.username %}"><b>Диагностика</b></a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                    <div class="" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link text-white"
                            href="{% url 'diagnostic:admin-dashboard' admin.username %}">
                            <button type="submit" class="btn btn-white btn-sm">Назад к панели</button>
                        </a>
                    </li>

                </ul>
            </div>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container inner-content mt-">
        <div class="row">

            <!-- {% for test in all_added_tests %}
            <div class="col-3">
                <div class="card test-box mt-5 mb-4">
                    <img src="{{ test.image.url }}" class="card-img-top" alt="..." width="100%">

                    <div class="card-body">

                        <h5 class="card-title">{{ test.test_name }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ test.category }}</h6>
                        <p class="card-text center">{{ test.center }}</p>
                        <p class="card-text">Discount: {{ test.discount }}</p>
                        <p class="card-text text-danger">Price: {{ test.price }} TK</p>
                        <p class="card-text">{{ test.active_status }}</p>
                    </div>

                    <a href="{% url 'medicine_tests:delete_test' test.id admin.username %}">
                        <button type="submit" class="btn btn-danger">DELETE</button>
                        <br><br>
                    </a>

                    <a href="{% url 'medicine_tests:edit-test' test.id admin.username %}"><button type="submit"
                            class="btn btn-warning">
                            EDIT</button>
                    </a>
                </div>
            </div>
            {% endfor %} -->



            {% for test in all_added_tests %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="test-box">
                    <div class="card-title">
                        <img src="{{ test.image.url }}" class="card-img-top" alt="..." width="100%">
                    </div>

                    <div class="card-body">
                        <p class="card-subtitle mb-2 text-muted">{{ test.category }}</p>

                        <h6 class="">
                            <a href="{% url 'medicine_tests:test-details' test.id %}">{{ test.test_name }}</a>
                        </h6>

                        <p class="card-text">{{ test.center }}</p>
                        <p class="card-text text-dange price my-0">Скидка: <span id="price">{{ test.discount }}</span>
                            
                        </p>
                        <p class="card-text text-dange price mt-0">Цена: <span id="price">{{ test.price }}</span>
                        </p>
                        <!-- <p class="card-text">{{ test.active_status }}</p> -->

                        <div class="btn-group pb-3">
                            <!-- Delete -->
                            <a href="{% url 'medicine_tests:delete_test' test.id admin.username %}" class="btn btn-danger">
                                DELETE
                            </a>
                            <!-- Delete -->

                            <!-- Edit -->
                            <a href="{% url 'medicine_tests:edit-test' test.id admin.username %}" class="btn btn-warning">
                                EDIT
                            </a>
                            <!-- Edit -->
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- All added tests Paginator -->
            <ul class="pagination">
                <li class="page-item">

                    {% if all_added_tests.has_previous %}
                    <a class="page-link" href="?page={{ all_added_tests.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="false">&laquo;</span>
                    </a>
                    {% endif %}

                </li>
                <li class="page-item">
                    <a class="page-link" href="#">Page {{ all_added_tests.number }} of
                        {{ all_added_tests.paginator.num_pages }}.</a>
                </li>
                <li class="page-item">

                    {% if all_added_tests.has_next %}

                    <a class="page-link" href="?page={{ all_added_tests.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                    {% endif %}
                </li>
            </ul>
            <!-- All added tests Paginator -->

        </div>
    </div>

    {#    {% for staff in staffs_by_center %}#}
    {#        <li>{{ staff.username }}</li>#}
    {#    {% endfor %}#}

    <div class="footer bg-dark text-white text-center py-2">
        <div class="d-box px-2">
            <a class="text-white" href="{% url 'developers' %}" target="_blank" data-toggle="tooltip"
                data-placement="top" title="About Developers">About Developers</a>
        </div>
    </div>



    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>
    <script>
        $(document).ready(function () {
            $(".dropdown-btn").click(function () {
                $('.dropdown').toggle();
            });
        });
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

Diagnostic_Laboratory/templates/medicine_tests/confirm_payment_message.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Подтверждение | Диагностика</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>

</head>

<body class="common-bg pt-0 ">

    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <div class="container my-4">
        <div class="card-width">
            <div class="card card-form">
                <div class="card-header bg-dark text-center py-">
                    <h3 class="text-white mb-0 text-capitalize">Подтверждение ваучера</h3>
                </div>
                <div class="card-bottom-img"></div>

                <div class="card-body">
                    {% if order_details.staff_check == True and order_details.accepted == True %}
                    <div class="alert alert-success"> <strong>Заказ одобрен</strong> </div>
                    <!-- <b style="color: limegreen"></b> -->
                    <!-- <hr> -->
                    {% elif order_details.staff_check == True and order_details.accepted == False %}
                    <div class="alert alert-danger"> <strong>Отказано... Попытайтесь снова</strong> </div>
                    <!-- <b style="color: red"></b> -->
                    <!-- <hr> -->
                    {% endif %}


                    <div class="row">

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Имя</p>
                                <p>{{ order_details.client_info.profile_name }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Анализ</p>
                                <p>{{ order_details.test_info.test_name }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Email</p>
                                <p>{{ order_details.client_info.user.email }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Мед. центр</p>
                                <p>{{ order_details.test_info.center.name  }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Зарезервированное время</p>
                                <p>{{ order_details.booked_time_slot }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Дата бронирования</p>
                                <p>{{ order_details.booked_date }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Итоговая стоимость</p>
                                <p>{{ total_price }} </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Оплата</p>
                                <p>{{  order_details.payment_method }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Статус оплаты</p>
                                <p>{{  order_details.payment_type }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Телефон</p>
                                <p>{{ order_details.contact_no }} </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Адрес</p>
                                <p>{{ order_details.client_info.address }}</p>
                            </div>
                        </div>

                    </div>

                    <div class="row mt-3">

                        {% if request.user.is_authenticated %}
                        <div class="col-xs-12 col-sm-6 col-md-12">
                            <a href="{% url 'home' %}" class="btn btn-dark custom-bt text-white w-100 btn-s">
                                Назад на главную
                            </a>
                        </div>
                        {% else %}

                        {% if order_details.staff_check == False and order_details.accepted == False %}
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <a href="{% url 'medicine_tests:staff-approved' order_details.id staff_username %}"
                                class="btn btn-success text-white  w-100">
                                Одобрить
                            </a>

                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <a href="{% url 'medicine_tests:staff-rejected' order_details.id staff_username %}"
                                class="btn btn-danger text-white w-100">
                                Отказать
                            </a>
                        </div>
                        {% endif %}

                        {% if order_details.staff_check == True and order_details.accepted == True and order_details.came_for_test == False %}
                        <div class="col-12">
                            <a href="{% url 'medicine_tests:came-for-test' order_details.id staff_username %}"
                                class="btn btn-dark custom-bt text-white w-100">
                                Сдал анализ
                            </a>
                        </div>
                        {% endif %}

                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>



    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>
</body>

</html>