Diagnostic_Laboratory/Diagnostic_Laboratory/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import home
from .views import DevelopersView


urlpatterns = [


    # Superuser
    path('admin/', admin.site.urls),

    # Home
    path('', home, name='home'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (diagnostic)
    path('', include('diagnostic.urls', namespace='diagnostic')),

    # App3 (medicine_tests)
    path('', include('medicine_tests.urls', namespace='medicine_tests')),

    # App3 (report_processing)
    path('', include('report_processing.urls', namespace='report_processing')),

    # Allauth (built-in)
    path('accounts/', include('allauth.urls')),

    # Developers
    path('developers/', DevelopersView.as_view(), name='developers'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Diagnostic_Laboratory/diagnostic/urls.py
from django.urls import path

from .views import (

    search_paginator,

    admin_login,
    admin_logout,
    admin_dashboard,

    staff_login,
    staff_logout,
    staff_dashboard,

    center_details,

)


app_name = 'diagnostic'

urlpatterns = [

    path('all-centers/', search_paginator, name='all-centers'),

    path('admin-login/', admin_login, name='admin-login'),
    path('admin-logout/', admin_logout, name='admin-logout'),
    path('admin-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),

    path('staff-login/', staff_login, name='staff-login'),
    path('staff-logout/', staff_logout, name='staff-logout'),
    path('staff-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('staff-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),

    path('center-details/<int:id>/', center_details, name='center-details'),


]

Diagnostic_Laboratory/medicine_tests/urls.py
from django.urls import path

from .views import (

    all_tests,
    test_details,

    test_order,
    order_details_info,

    test_categories,
    categorise_tests,

    staff_approved,
    staff_rejected,

    add_test_by_admin,
    add_category_by_admin,
    filtered_categories_by_admin,
    filtered_categories_for_staff,

    delete_test,
    edit_test,

    edit_category,
    delete_category,

    all_tests_list_for_staff,
    added_tests_list_for_staff_admin,

    confirm_payment_message,

    came_for_test,

    total_test_count_center_staff,

)


app_name = 'medicine_tests'


urlpatterns = [

    path('all-medicine_tests/', all_tests, name='all-medicine_tests'),

    path('categories/', test_categories, name='categories'),

    path('categorise-medicine_tests/<int:id>/', categorise_tests, name='categorise-medicine_tests'),

    path('test-details/<int:id>/', test_details, name='test-details'),

    path('order/<int:id>/', test_order, name='order'),

    path('order-details/<int:id>/', order_details_info, name='order-details'),

    path('staff-approved/<int:id>/<username>/', staff_approved, name='staff-approved'),

    path('staff-rejected/<int:id>/<username>/', staff_rejected, name='staff-rejected'),

    path('add-test/<username>/', add_test_by_admin, name='add-test'),

    path('add-category/<username>/', add_category_by_admin, name='add-category'),

    path('filtered-categories-by-admin/<username>/', filtered_categories_by_admin, name='filtered-categories-by-admin'),

    path('filtered-categories-for-staff/<username>/', filtered_categories_for_staff, name='filtered-categories-for-staff'),

    path('all-medicine_tests-list-staff/<username>/', all_tests_list_for_staff, name='all-medicine_tests-list-staff'),

    path('added-medicine_tests-list-staff-admin/<username>/', added_tests_list_for_staff_admin, name='added-medicine_tests-list-staff-admin'),

    path('delete-test/<int:id>/<username>/', delete_test, name='delete_test'),

    path('delete-category/<int:id>/<username>/', delete_category, name='delete-category'),

    path('edit-test/<int:id>/<username>/', edit_test, name='edit-test'),

    path('edit-category/<int:id>/<username>/', edit_category, name='edit-category'),

    path('confirm-payment-message/<int:id>/', confirm_payment_message, name='confirm-payment-message'),

    path('staff-confirm-payment-message/<int:id>/<username>/', confirm_payment_message, name='staff-confirm-payment-message'),

    path('came-for-test/<int:id>/<username>/', came_for_test, name='came-for-test'),

    path('total-test-count-center-staff/<int:id>/', total_test_count_center_staff, name='total-test-count-center-staff'),


]

Diagnostic_Laboratory/report_processing/urls.py
from django.urls import path

from .views import all_reports, single_report_details, complete_due_payment


app_name = 'report_processing'

urlpatterns = [

    path('all-reports/', all_reports, name='all-reports'),

    path('single-report-details/<int:id>/', single_report_details, name='single-report-details'),

    path('complete-due-payment/<int:id>/<int:report_id>/', complete_due_payment, name='complete-due-payment'),

]

Diagnostic_Laboratory/diagnostic/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


class DiagnosticCenter(models.Model):
    name = models.CharField(max_length=250, blank=False)
    image = models.ImageField(default='default_center.jpg', upload_to='diagnostic_center_pics')
    email = models.EmailField(blank=True)
    contact_no = models.CharField(max_length=20, blank=False)
    website = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=150, blank=False)

    class Meta:
        verbose_name_plural = 'Diagnostic Centers'


    def __str__(self):
        return self.name


class DiagnosticStaff(models.Model):
    username = models.CharField(max_length=20, unique=True, blank=False)
    password = models.CharField(max_length=100, unique=True,  blank=False)

    admin = models.BooleanField(default=False)

    center = models.ForeignKey(DiagnosticCenter, on_delete=models.CASCADE, related_name='center_staffs')

    class Meta:
        verbose_name_plural = 'Diagnostic Staffs'

    def __str__(self):
        return self.username


class DiagnosticAdmin(models.Model):
    username = models.CharField(max_length=20, unique=True, blank=False)
    password = models.CharField(max_length=100, unique=True, blank=False)

    admin = models.BooleanField(default=True)

    center = models.ForeignKey(DiagnosticCenter, on_delete=models.CASCADE, related_name='center_admins')
    staff = models.ManyToManyField(DiagnosticStaff)

    class Meta:
        verbose_name_plural = 'Diagnostic Admins'

    def __str__(self):
        return self.username

Diagnostic_Laboratory/diagnostic/forms.py
from django import forms
from django.forms import TextInput

from .models import DiagnosticAdmin, DiagnosticStaff, DiagnosticCenter


class AdminLoginForm(forms.ModelForm):
    class Meta:
        model = DiagnosticAdmin

        fields = ['username', 'password']

        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'password': TextInput(attrs={'class': 'form-control'}),
        }


class StaffLoginForm(forms.ModelForm):
    class Meta:
        model = DiagnosticStaff

        fields = ['username', 'password']

        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'password': TextInput(attrs={'class': 'form-control'}),
        }

Diagnostic_Laboratory/diagnostic/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q


from medicine_tests.models import TestOrder, Test
from report_processing.models import PaymentValidation
from report_processing.forms import PaymentValidationForm

from .models import DiagnosticCenter, DiagnosticAdmin, DiagnosticStaff
from .forms import AdminLoginForm, StaffLoginForm

########################################################################################################################


def search_paginator(request):
    Centers = DiagnosticCenter.objects.all()

    query = request.GET.get('q')
    if query:
        Centers = Centers.filter(
            Q(name__icontains=query) |
            Q(website__icontains=query)
        )
        print(Centers)

    paginator = Paginator(Centers, 12)
    page = request.GET.get('page')
    all_centers = paginator.get_page(page)

    context = {'Centers': all_centers,}
    template_name = 'diagnostic/all_centers.html'

    return render(request, template_name, context)


########################################################################################################################


def admin_login(request):
    admin_login_form = AdminLoginForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            DiagnosticAdmin.objects.get(username=username, password=password)
            return redirect('diagnostic:admin-dashboard', username)

        except DiagnosticAdmin.DoesNotExist:
            return redirect('diagnostic:admin-login')

    template = 'diagnostic/admin_login.html'

    context = {'admin_login_form': admin_login_form}

    return render(request, template, context)


########################################################################################################################


def admin_dashboard(request, username=None):
    admin = DiagnosticAdmin.objects.get(username=username)
    validated_orders = TestOrder.objects.filter(accepted=True, validation=True, test_info__center=admin.center)
    completed_orders = PaymentValidation.objects.filter(approved_order__payment_type='Full Payment')

    # Completed Paginator
    paginator = Paginator(completed_orders, 10)
    page = request.GET.get('page')
    completed_orders_paginator_data = paginator.get_page(page)

    template = 'diagnostic/admin_dashboard.html'

    context = {
        'admin': admin,
        'completed_orders': completed_orders_paginator_data
    }

    return render(request, template, context)


########################################################################################################################


def admin_logout(request):
    messages.success(request, 'Logged Out.', extra_tags='html_safe')
    return redirect('diagnostic:admin-login')


########################################################################################################################


def staff_login(request):
    staff_login_form = StaffLoginForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            DiagnosticStaff.objects.get(username=username, password=password)
            return redirect('diagnostic:staff-dashboard', username)

        except DiagnosticStaff.DoesNotExist:
            return redirect('diagnostic:staff-login')

    template = 'diagnostic/staff_login.html'

    context = {'staff_login_form': staff_login_form}

    return render(request, template, context)


########################################################################################################################


def staff_dashboard(request, id=None, username=None):

    staff = DiagnosticStaff.objects.get(username=username)
    admins = DiagnosticAdmin.objects.filter(staff=staff)

    # Step 0
    pending_tests = TestOrder.objects.filter(accepted=False, order_confirmed=True, staff_check=False,
                                             test_info__center=staff.center)

    # Step 1
    confirmed_tests = TestOrder.objects.filter(accepted=True, order_confirmed=True, test_info__center=staff.center)

    # Step 4
    half_payment_orders = TestOrder.objects.filter(accepted=True, order_confirmed=True, payment_type='Half Payment',
                                                   test_info__center=staff.center)
    # Step 2 + 3
    came_for_tests = TestOrder.objects.filter(accepted=True, test_info__center=staff.center)

    # Step 5 + 6
    full_payment_orders = TestOrder.objects.filter(accepted=True, order_confirmed=True, payment_type='Full Payment',
                                                   test_info__center=staff.center)
    # Step 7
    # all_orders = PaymentValidation.objects.all()
    completed_orders = PaymentValidation.objects.filter(approved_order__payment_type='Full Payment')

    # Step 8
    sent_message_orders = PaymentValidation.objects.filter(approved_order__payment_type='Half Payment')

    """Counting"""
    count_pending_tests = pending_tests.count()
    count_confirmed_tests = confirmed_tests.count()
    count_came_for_tests = came_for_tests.count()
    count_half_payment_orders = half_payment_orders.count()
    count_full_payment_orders = full_payment_orders.count()
    count_completed_orders = completed_orders.count()

    # Pending Orders Paginator
    paginator = Paginator(pending_tests, 5)
    page = request.GET.get('page')
    pending_paginator_data = paginator.get_page(page)

    # Confirmed Orders Paginator
    paginator = Paginator(confirmed_tests, 5)
    page = request.GET.get('page')
    confirmed_paginator_data = paginator.get_page(page)

    # Half payment Orders Paginator
    paginator = Paginator(half_payment_orders, 5)
    page = request.GET.get('page')
    half_payment_paginator_data = paginator.get_page(page)

    # Came for test Paginator
    paginator = Paginator(came_for_tests, 5)
    page = request.GET.get('page')
    came_for_paginator_data = paginator.get_page(page)

    # Full payment Paginator
    paginator = Paginator(full_payment_orders, 5)
    page = request.GET.get('page')
    full_payment_paginator_data = paginator.get_page(page)

    # Completed orders Paginator
    paginator = Paginator(completed_orders, 10)
    page = request.GET.get('page')
    completed_orders_paginator_data = paginator.get_page(page)

    # All orders Paginator
    # paginator = Paginator(all_orders, 20)
    # page = request.GET.get('page')
    # all_orders_paginator_data = paginator.get_page(page)

    # Sent message orders Paginator
    paginator = Paginator(sent_message_orders, 10)
    page = request.GET.get('page')
    sent_message_orders_paginator_data = paginator.get_page(page)

    if request.method == 'POST':
        form = PaymentValidationForm(request.POST, request.FILES)

        if form.is_valid():

            payment_form = form.save(commit=False)

            order = TestOrder.objects.get(id=id)
            order.validation = True
            order.save()

            payment_form.approved_order = order
            payment_form.save()

    template = 'diagnostic/staff_dashboard.html'

    context = {
        'staff': staff,
        'admins': admins,

        'pending_tests': pending_paginator_data,
        'confirmed_tests': confirmed_paginator_data,
        'half_payment_orders': half_payment_paginator_data,
        'came_for_tests': came_for_paginator_data,
        'full_payment_orders': full_payment_paginator_data,
        'completed_orders': completed_orders_paginator_data,
        'sent_message_orders': sent_message_orders_paginator_data,

        'staff_username': username,
        'payment_form': PaymentValidationForm(),

        # counting
        'count_pending_tests': count_pending_tests,
        'count_confirmed_tests': count_confirmed_tests,
        'count_came_for_tests': count_came_for_tests,
        'count_half_payment_orders': count_half_payment_orders,
        'count_full_payment_orders': count_full_payment_orders,
        'count_completed_orders': count_completed_orders,

    }

    return render(request, template, context)

########################################################################################################################


def staff_logout(request):
    return redirect('diagnostic:staff-login')

########################################################################################################################


def center_details(request, id=id):
    single_center = DiagnosticCenter.objects.get(id=id)
    tests_by_center = Test.objects.filter(center__id=id)

    template = 'diagnostic/center_details.html'

    context = {
        'tests_by_center': tests_by_center,
        'single_center': single_center,
    }

    return render(request, template, context)

########################################################################################################################

Diagnostic_Laboratory/templates/diagnostic/admin_dashboard_BK.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Dashboard | Диагностика</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body>
    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-warning"
                href="{% url 'diagnostic:admin-dashboard' admin.username %}"><b>ODLRS</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item user-profile">
                        <a class="nav-link d-flex dropdown-btn" href="#">
                            <img src="{% static 'images/admin-staff.png' %}" alt="" class="rounded-circle">
                            <span class=" dropdown-toggle text-white ml-2">Администратор</span>
                        </a>

                        <ul class="dropdown">
                            <li class="text-center">
                                <img src="{% static 'images/admin-staff.png' %}" alt="" class="rounded-circle mb-2">
                                <a href="http://localhost:8000/admin-dashboard/labaid_admin_1">Панель администратора</a>
                            </li>
                            <div class="dropdown-divider"></div>

                            <li class="dropdown-item">
                                <a href="{% url 'medicine_tests:add-category' admin.username %}">
                                    Добавить новую категорию
                                </a>
                            </li>
                            <li class="dropdown-item">
                                <a href="{% url 'medicine_tests:add-test' admin.username %}">Добавить новый анализ</a>
                            </li>
                            <li class="dropdown-item">
                                <a href="{% url 'medicine_tests:filtered-categories-by-admin' admin.username %}">
                                    Последние категории
                                </a>
                            </li>
                            <li class="dropdown-item">
                                <a href="{% url 'medicine_tests:added-medicine_tests-list-staff-admin' admin.username %}">
                                    Последние анализы
                                </a>
                            </li>
                            <li class="dropdown-item">
                                <a class="" href="{% url 'diagnostic:admin-logout' %}">Выход</a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container inner-content" style="min-height: 520px">

        <div class="staff bg-dark text-white text-center p-4 mb-4">
            <h1> <strong>Панель администратора</strong> </h1>

            <div class="row mt-4 mx-4 py-3 bg-warning text-dark">
                <div class="col">
                    <h6 class="text-white mb-0"> <strong class="text-dark">Мед. центр:</strong>
                        <b style="color: orangered">{{ admin.center }}</b>
                    </h6>
                </div>
                <div class="col">
                    <h6 class="text-white mb-0"> <strong class="text-dark">Администратор:</strong>
                        <b style="color: orangered">{{ admin.username }}</b>
                    </h6>
                </div>
            </div>

        </div>


        <div class="staff-info">
            <div class="row">

                <!-- Step 7 Completed Orders -->
                <div class="col-md-12">
                    <table class="table table-striped table-bordered table-hover mb-4">
                        <thead>
                            <tr class="bg-success text-white">
                                <th colspan="6">Завершённые заказы</th>
                            </tr>
                            <tr>
                                <th width="15px">No.</th>
                                <th>Заказы</th>
                                <th>Дата</th>
                                <th>Результаты</th>
                                <th>Статус</th>
                            </tr>
                        </thead>

                        <tbody>

                            {% for report in completed_orders %}
                            <tr>
                                <td> {{ forloop.counter }} </td>

                                <td><a href="{% url 'report_processing:single-report-details' report.id %}"><b
                                            style="color: green">
                                            {{ report.approved_order.test_info.test_name }}</b></a>
                                </td>

                                <td style="color: green">{{ report.datetime }}</td>

                                <td style="color: blue">{{ report.upload_report }}</td>

                                <td><b style="color: green">{{ report.send_message }}</b></td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                    <!-- completed Paginator -->
                    <ul class="pagination">
                        <li class="page-item">

                            {% if completed_orders.has_previous %}
                            <a class="page-link" href="?page={{ completed_orders.previous_page_number }}"
                                aria-label="Previous">
                                <span aria-hidden="false">&laquo;</span>
                            </a>
                            {% endif %}

                        </li>
                        <li class="page-item">
                            <a class="page-link" href="#">Страница {{ completed_orders.number }} of
                                {{ completed_orders.paginator.num_pages }}.</a>
                        </li>
                        <li class="page-item">

                            {% if completed_orders.has_next %}

                            <a class="page-link" href="?page={{ completed_orders.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                    <!-- completed Paginator -->
                    <br>
                </div>
                <!-- Step 7 End -->


                <!-- Staffs Table -->
                <div class="col-12">
                    <table class="table table-striped table-bordered table-hover mb-4">
                        <thead>
                            <tr class="bg-primary text-white">
                                <th colspan="2"> Сотрудники </th>
                            </tr>
                            <tr>
                                <th>SL.</th>
                                <th>Сотрудники</th>
                            </tr>
                        </thead>

                        <tbody>

                            {% for s in admin.staff.all %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <th>{{ s.username }}</th>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- Staffs Table End -->

            </div>
        </div>

    </div>


    <div class="footer bg-dark text-white text-center py-2">
        <p class="mb-0"> &copy; Copyrights. All rights reserved. </p>
    </div>


        {% for s in admin.staff.all %}
        <tr>
            <th scope="row" style="color: blue">{{ forloop.counter }}</th>
            <th style="color: blue">{{ s.username }}</th>
        </tr>
        {% endfor %}
    </table>
    <br>
    <hr>
    <h3 style="color: forestgreen">Активные заказы</h3>

    {% for test in confirmed_tests %}

    <li><a href="{% url 'medicine_tests:order-details' test.id %}">{{ test.test_info.test_name }}</a></li><br>

    {% endfor %} -->


    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>
    <script>
        $(document).ready(function () {
            $(".dropdown-btn").click(function () {
                $('.dropdown').toggle();
            });
        });
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

Diagnostic_Laboratory/templates/diagnostic/all_centers.html
{% extends 'base.html' %}

{% block title %}Все мед. центры | Диагностика{% endblock %}

{% block content %}


<div class="container inner-content">

    <div class="search-box bg-success p- my-">
        <div class="container">
            <h3 class="text-white mb-">Поиск центра</h3>

            <form class="search" action="" method="GET">

                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" name='q' placeholder="type any center's name..."
                        aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary" class="searchButton">
                            Поиск
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <div class="center-lists mt-">
        <div class="row">

            {% for centers in Centers %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card test-box mt-4 mb-0">
                    <div class="card-title">
                        <img src="{{ centers.image.url }}" class="card-img-top" alt="..." width="100%">
                    </div>

                    <div class="card-body">
                        <a href="{% url 'diagnostic:center-details' centers.id %}">{{ centers.name }}</a>

                        <p class=""> <span>{{ centers.email }}</span></p>
                        <p class=""> <span>{{ centers.contact_no }}</span></p>
                        <p class=""> <span>{{ centers.website }}</span> </p>

                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>


    <ul class="pagination">
        <li class="page-item">
            {% if Centers.has_previous %}
            <a class="page-link" href="?page={{ Centers.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="false">&laquo;</span>
            </a>
            {% endif %}

        </li>
        <li class="page-item">
            <a class="page-link" href="#">Страница {{ Centers.number }} of {{ Centers.paginator.num_pages }}.</a>
        </li>
        <li class="page-item">
            {% if Centers.has_next %}
            <a class="page-link" href="?page={{ Centers.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
            {% endif %}
        </li>
    </ul>
    </nav>

</div>

{% endblock %}

Diagnostic_Laboratory/templates/diagnostic/center_details.html
{% extends 'base.html' %}

{% block title %}Медицинский центр | Диагностика{% endblock %}

{% block content %}


<div class="inner-content">
    <div class="container">

        <!-- all tests -->
        <div class="row">
            {% for test in tests_by_center %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card test-box">
                    <div class="card-title">
                        <img src="{{ test.image.url }}" class="card-img-top" alt="..." width="100%">
                    </div>

                    <div class="card-body">
                        <p class="card-subtitle mb-2 text-muted">{{ test.category }}</p>

                        <h6 class="">
                            <a href="{% url 'medicine_tests:test-details' test.id %}">{{ test.test_name }}</a>
                        </h6>

                        <p class="card-text">{{ test.center }}</p>


                        <p class="card-text text-dange price">Цена: <span id="price">{{ test.price }}</span></p>
                        <!-- <p class="card-text">{{ test.active_status }}</p> -->

                        <a class="btn btn-sm btn btn-success text-center" href="{% url 'medicine_tests:order' test.id %}"
                            type="submit">
                            Заказ
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>



        <!-- {% for test in tests_by_center %}


        {% endfor %}
        <br> -->
    </div>

</div>

{% endblock %}