Diagnostic_Laboratory/Diagnostic_Laboratory/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import home
from .views import DevelopersView


urlpatterns = [


    # Superuser
    path('admin/', admin.site.urls),

    # Home
    path('', home, name='home'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (diagnostic)
    path('', include('diagnostic.urls', namespace='diagnostic')),

    # App3 (medicine_tests)
    path('', include('medicine_tests.urls', namespace='medicine_tests')),

    # App3 (report_processing)
    path('', include('report_processing.urls', namespace='report_processing')),

    # Allauth (built-in)
    path('accounts/', include('allauth.urls')),

    # Developers
    path('developers/', DevelopersView.as_view(), name='developers'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Diagnostic_Laboratory/custom_users/urls.py
from django.urls import path

from .views import (

    profile,
    profile_edit,
    orders_by_user,
    filtered_report,
)


app_name = 'custom_users'

urlpatterns = [

    path('profile/', profile, name='profile'),

    path('profile-edit/', profile_edit, name='profile-edit'),

    path('orders-by-user/', orders_by_user, name='orders-by-user'),

    path('filtered-reports-by-user/<int:id>/', filtered_report, name='filtered-reports-by-user')

]

Diagnostic_Laboratory/diagnostic/urls.py
from django.urls import path

from .views import (

    search_paginator,

    admin_login,
    admin_logout,
    admin_dashboard,

    staff_login,
    staff_logout,
    staff_dashboard,

    center_details,

)


app_name = 'diagnostic'

urlpatterns = [

    path('all-centers/', search_paginator, name='all-centers'),

    path('admin-login/', admin_login, name='admin-login'),
    path('admin-logout/', admin_logout, name='admin-logout'),
    path('admin-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),

    path('staff-login/', staff_login, name='staff-login'),
    path('staff-logout/', staff_logout, name='staff-logout'),
    path('staff-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('staff-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),

    path('center-details/<int:id>/', center_details, name='center-details'),


]

Diagnostic_Laboratory/medicine_tests/urls.py
from django.urls import path

from .views import (

    all_tests,
    test_details,

    test_order,
    order_details_info,

    test_categories,
    categorise_tests,

    staff_approved,
    staff_rejected,

    add_test_by_admin,
    add_category_by_admin,
    filtered_categories_by_admin,
    filtered_categories_for_staff,

    delete_test,
    edit_test,

    edit_category,
    delete_category,

    all_tests_list_for_staff,
    added_tests_list_for_staff_admin,

    confirm_payment_message,

    came_for_test,

    total_test_count_center_staff,

)


app_name = 'medicine_tests'


urlpatterns = [

    path('all-medicine_tests/', all_tests, name='all-medicine_tests'),

    path('categories/', test_categories, name='categories'),

    path('categorise-medicine_tests/<int:id>/', categorise_tests, name='categorise-medicine_tests'),

    path('test-details/<int:id>/', test_details, name='test-details'),

    path('order/<int:id>/', test_order, name='order'),

    path('order-details/<int:id>/', order_details_info, name='order-details'),

    path('staff-approved/<int:id>/<username>/', staff_approved, name='staff-approved'),

    path('staff-rejected/<int:id>/<username>/', staff_rejected, name='staff-rejected'),

    path('add-test/<username>/', add_test_by_admin, name='add-test'),

    path('add-category/<username>/', add_category_by_admin, name='add-category'),

    path('filtered-categories-by-admin/<username>/', filtered_categories_by_admin, name='filtered-categories-by-admin'),

    path('filtered-categories-for-staff/<username>/', filtered_categories_for_staff, name='filtered-categories-for-staff'),

    path('all-medicine_tests-list-staff/<username>/', all_tests_list_for_staff, name='all-medicine_tests-list-staff'),

    path('added-medicine_tests-list-staff-admin/<username>/', added_tests_list_for_staff_admin, name='added-medicine_tests-list-staff-admin'),

    path('delete-test/<int:id>/<username>/', delete_test, name='delete_test'),

    path('delete-category/<int:id>/<username>/', delete_category, name='delete-category'),

    path('edit-test/<int:id>/<username>/', edit_test, name='edit-test'),

    path('edit-category/<int:id>/<username>/', edit_category, name='edit-category'),

    path('confirm-payment-message/<int:id>/', confirm_payment_message, name='confirm-payment-message'),

    path('staff-confirm-payment-message/<int:id>/<username>/', confirm_payment_message, name='staff-confirm-payment-message'),

    path('came-for-test/<int:id>/<username>/', came_for_test, name='came-for-test'),

    path('total-test-count-center-staff/<int:id>/', total_test_count_center_staff, name='total-test-count-center-staff'),


]

Diagnostic_Laboratory/templates/add_category.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Добавить категорию | Диагностика</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body class="common-bg">

    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-white" href="#"><b>Диагностика</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item user-profile">
                        <a class="nav-link d-flex dropdown-btn" href="#">
                            <img src="{% static 'images/admin-staff.png' %}" alt="" class="rounded-circle">
                            <span class=" dropdown-toggle text-white ml-2">Администратор</span>
                        </a>

                        <ul class="dropdown">
                            <li class="text-center">
                                <img src="{% static 'images/admin-staff.png' %}" alt="" class="rounded-circle mb-2">
                                <a href="http://localhost:8000/admin-dashboard/labaid_admin_1">Панель администратора</a>
                            </li>
                            <div class="dropdown-divider"></div>
                            <li class="dropdown-item">
                                <a href="{% url 'diagnostic:admin-logout' %}">Выход</a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container inner-content">
        <div class="card-width">
            <div class="card my-4">
                <div class="card-header bg-dark text-center py-">
                    <h2 class="text-white mb-0 text-uppercase">Добавить категорию</h2>
                </div>
                <div class="card-bottom-img"></div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                        {{ category_add_form.as_p }}

                        <button class="btn btn-dark w-100 mt-4 " type="submit">Добавить</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="footer text-white text-center bg-dark py-3" style="position: relative">
        <div class="d-box px-2">
            <a class="text-white" href="{% url 'developers' %}" target="_blank" data-toggle="tooltip"
                data-placement="top" title="About Developers">About Developers</a>
        </div>
    </div>


    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>
    <script>
        $(document).ready(function () {
            $(".dropdown-btn").click(function () {
                $('.dropdown').toggle();
            });
        });
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

Diagnostic_Laboratory/templates/add_test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Test | ODLRS</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body class="common-bg">
    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-white" href="#"><b>Диагностика</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item user-profile">
                        <a class="nav-link d-flex dropdown-btn" href="#">
                            <img src="{% static 'images/admin-staff.png' %}" alt="" class="rounded-circle">
                            <span class=" dropdown-toggle text-white ml-2">Администратор</span>
                        </a>

                        <ul class="dropdown">
                            <li class="text-center">
                                <img src="{% static 'images/admin-staff.png' %}" alt="" class="rounded-circle mb-2">
                                <a href="http://localhost:8000/admin-dashboard/labaid_admin_1">Панель администратора</a>
                            </li>
                            <div class="dropdown-divider"></div>
                            <li class="dropdown-item">
                                <a href="{% url 'diagnostic:admin-logout' %}">Выход</a>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

    <div class="container inner-conten">
        <div class="card-width">
            <div class="card card-form mb-5">
                <div class="card-header bg-dark text-center py-">
                    <h2 class="text-white mb-0 text-uppercase"> Добавить анализ </h2>
                </div>
                <div class="card-bottom-img"></div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                        {{ test_add_form.as_p }}

                        <button class="btn btn-dark w-100 mt-3" type="submit">Добавить</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="footer bg-dark text-white text-center py-3">
        <div class="d-box px-2">
            <a class="text-white" href="{% url 'developers' %}" target="_blank" data-toggle="tooltip"
                data-placement="top" title="About Developers">Онлайн-система диагностической лаборатории 2022</a>
        </div>
    </div>


    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>
    <script>
        $(document).ready(function () {
            $(".dropdown-btn").click(function () {
                $('.dropdown').toggle();
            });
        });
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

Diagnostic_Laboratory/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>{% block title %}{% endblock %}</title>

	<!-- fontawesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.0/css/all.css"
		integrity="sha384-Mmxa0mLqhmOeaE8vgOSbKacftZcsNYDjQzuCOm6D02luYSzBG8vpaOykv9lFQ51Y" crossorigin="anonymous">


	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	<script src="{% static 'js/jquery.min.js' %}"></script>

</head>

<body>

	<!-- loader -->
	<div class="fakeLoader"></div>
	<!-- loader -->


	<nav class="navbar navbar-expand-lg bg-success">
		<div class="container">
			<a class="navbar-brand text-white" href="{% url 'home' %}"><b>Диагностика</b></a>
			<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

				<i class="fa fa-bars text-white"></i>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item ">
						<a class="nav-link" href="{% url 'home' %}">Главная</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'diagnostic:all-centers' %}">Центры</a>
					</li>
					<li class="nav-item ">
						<a class="nav-link" href="{% url 'medicine_tests:all-medicine_tests' %}">Анализы</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'medicine_tests:categories' %}">Виды анализов</a>
					</li>


					{% if user.is_authenticated %}
					<li class="nav-item user-profile">
						<a class="nav-link d-flex dropdown-btn" href="#">
							<img src="{{ user.customer_profile.image.url }}" alt="" class="rounded-circle">
							<span class=" dropdown-toggle ml-2">{{user.username}} </span>
						</a>

						<ul class="dropdown">
							<li class="text-center">
								<img src="{{ user.customer_profile.image.url }}" alt="" class="rounded-circle">
								<p>{{ user.customer_profile.profile_name }}</p>
								<a href="{% url 'custom_users:profile-edit' %}">
									Редактировать профиль
				/				</a>
							</li>
							<div class="dropdown-divider"></div>
							<li class="dropdown-item">
								<a href="{% url 'custom_users:orders-by-user' %}"> Профиль</a>
							</li>
							<li class="dropdown-item">
								<a href="{% url 'custom_users:filtered-reports-by-user' user.id %}"> Отчёты</a>
							</li>
							<li class="dropdown-item">
								<a href="{% url 'account_logout' %}"> Выход</a>
							</li>
						</ul>
					</li>

					{% else %}
					<li class="nav-item ">
						<a class="nav-link" href="{% url 'account_login' %}">Вход</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'account_signup' %}">Регистрация</a>
					</li>
					{% endif %}

				</ul>
			</div>
		</div>
	</nav>


	{% block content %} {% endblock %} {% block extra_body %} {% endblock %}

	<div class="footer text-white text-center py-3 bg-dark">
		<div class="w-100 text-center d-flex justify-content-center">


			<div class="d-box px-2">
				<a class="text-white" target="_blank" data-toggle="tooltip"
					data-placement="top" title="Онлайн-система диагностической лаборатории 2022">Онлайн-система диагностической лаборатории 2022</a>
			</div>


		</div>
	</div>








	<script src="{% static 'js/fakeLoader.min.js' %}"></script>
	<script>
		$.fakeLoader();
		$(function () {
			$('[data-toggle="tooltip"]').tooltip()
		})
	</script>

	<script>
		$(document).ready(function () {
			$(".dropdown-btn").click(function (e) {
				e.preventDefault();
				$('.dropdown').toggle();
			});
		});
	</script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
	</script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

Diagnostic_Laboratory/templates/developer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Developers</title>
    <STYLE>A {text-decoration: none;} </STYLE>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
</head>

<body>
    <div class="container">
        <br>
        <h2>Developers:</h2>
        <br>
        <div class="jumbotron">
            <h4>
                1. <a href="https://www.linkedin.com/in/dzmitrybahdanovich/" target="_blank" title="D. Bahdanovich">D. Bahdanovich</a>
            </h4>
        </div>
    </div>

</body>
</html>

Diagnostic_Laboratory/templates/home.html
{% extends 'base.html' %}

{% block title %}Главная | Диагностика{% endblock %}

{% block content %}

<div class="header-image">
    <div class="container">
        <div class="header-content">
            <h1>Анализы и тесты</h1>
            <h2>бронирование</h2>
            <h5>закажи любой анализ</h5>

            <a href="#welcome" class="btn"> приступай <i class="fa fa-arrow-right pl-2"></i> </a>
        </div>
    </div>
</div>

<div class="welcome container text-dark" id="welcome">

    <!-- search -->
    <div class="search-box bg-success p- my-4">

        <div class="container">
            <h3 class="text-white mb-">Поиск анализов</h3>

            <form class="search" action="" method="GET">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" name='q' placeholder="type any test's name..."
                        aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary" class="searchButton">
                            НАЙТИ
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>


    <h3 class="text-uppercase mt-3">Все анализы</h3>
    <hr>
    <!-- all medicine_tests -->
    <div class="row mt-4">
        {% for test in all_tests_paginator_data %}
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="card test-box">
                <div class="card-title">
                    <img src="{{ test.image.url }}" class="card-img-top" alt="..." width="100%">
                </div>

                <div class="card-body pb-0">
                    <p class="card-subtitle mb-2 text-muted">{{ test.category }}</p>

                    <h6 class="">
                        <a href="{% url 'medicine_tests:test-details' test.id %}">{{ test.test_name }}</a>
                    </h6>

                    <p class="card-text">{{ test.center }}</p>
                    <p class="card-text text-dange price">Скидка: <span id="price">BYN {{ test.discount }}</span></p>
                    <p class="card-text text-dange price">Цена без скидки: <span id="price">BYN {{ test.price }}</span></p>
                    <!-- <p class="card-text">{{ test.active_status }}</p> -->

                    <a class="btn btn-sm btn btn-success text-center" href="{% url 'medicine_tests:order' test.id %}">
                        Заказ
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                {% if all_tests_paginator_data.has_previous %}
                <a class="page-link" href="?page=1" aria-label="Previous">
                    <span aria-hidden="false">&laquo;</span>
                </a>
                {% endif %}

            </li>
            <li class="page-item">
                <a class="page-link" href="#">Страница {{ all_tests_paginator_data.number }} of
                    {{ all_tests_paginator_data.paginator.num_pages }}</a>
            </li>
            <li class="page-item">
                {% if all_tests_paginator_data.has_next %}
                <a class="page-link" href="?page={{ all_tests_paginator_data.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>

{% endblock content %}

Diagnostic_Laboratory/templates/payment_method.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Заказ</title>
{% endblock %}

{% block header %}
    {% include 'components/header.html' %}
{% endblock %}


{% block content %}
    <div class="container">
    <div class="text-center">
        <h1>Заказ</h1>
    </div>
    <hr>

    <div class="container">
    <div class="row">
        <div class="col-md-6 text-lg-right text-md-right">
            <h5>Клиент:</h5>
        </div>
        <div class="col-md-6">
            <p>{{ customer.name }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-lg-right text-md-right">
            <h5>Телефон No:</h5>
        </div>
        <div class="col-md-6">
            <p>{{ customer.PhoneNo }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-lg-right text-md-right">
            <h5>Адрес:</h5>
        </div>
        <div class="col-md-6">
            <p>{{ order.address }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-lg-right text-md-right">
            <h5>Area:</h5>
        </div>
        <div class="col-md-6">
            <p>{{ order.area.name }}, {{ order.area.city }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 text-lg-right text-md-right">
            <h5>Type:</h5>
        </div>
        {% if order.frequency == '1' %}
            <div class="col-md-6">
                <p>Only Once</p>
            </div>
        {% elif order.frequency == '2' %}
            <div class="col-md-6">
                <p>Regular</p>
            </div>
        {% endif %}
    </div>
    <hr>
    <div class="text-center">
        <h1>Детали заказа</h1>
    </div>
    <hr>


    {% for items in quantity %}
        <div class="row">
            <div class="col-md-6 text-lg-right text-md-right">
                <h5>{{ items.0 }}</h5>
            </div>
            <div class="col-md-6">
                <p>{{ items.1 }}</p>
            </div>
        </div>
    {% endfor %}
    <hr>
    <div class="row">
        <div class="col-md-6 text-lg-right text-md-right">
            <h5>Итоговая цена : </h5>
        </div>
        <div class="col-md-6">
            <h5>{{ price }}</h5>
        </div>
    </div>
    <hr>


    <form action="/customer/order-confirmed/" method="post">
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" value="{{ order }}" class="btn btn-dark" name="order">Подтвердить</button>
        </div>
    </form>
    </div>
    </div>
{% endblock %}



{% block footer %}
    {% include 'components/footer.html' %}
{% endblock %}