Diagnostic_Laboratory/Diagnostic_Laboratory/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from .views import home
from .views import DevelopersView


urlpatterns = [


    # Superuser
    path('admin/', admin.site.urls),

    # Home
    path('', home, name='home'),

    # App1 (custom_users)
    path('', include('custom_users.urls', namespace='custom_users')),

    # App2 (diagnostic)
    path('', include('diagnostic.urls', namespace='diagnostic')),

    # App3 (medicine_tests)
    path('', include('medicine_tests.urls', namespace='medicine_tests')),

    # App3 (report_processing)
    path('', include('report_processing.urls', namespace='report_processing')),

    # Allauth (built-in)
    path('accounts/', include('allauth.urls')),

    # Developers
    path('developers/', DevelopersView.as_view(), name='developers'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Diagnostic_Laboratory/diagnostic/urls.py
from django.urls import path

from .views import (

    search_paginator,

    admin_login,
    admin_logout,
    admin_dashboard,

    staff_login,
    staff_logout,
    staff_dashboard,

    center_details,

)


app_name = 'diagnostic'

urlpatterns = [

    path('all-centers/', search_paginator, name='all-centers'),

    path('admin-login/', admin_login, name='admin-login'),
    path('admin-logout/', admin_logout, name='admin-logout'),
    path('admin-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),

    path('staff-login/', staff_login, name='staff-login'),
    path('staff-logout/', staff_logout, name='staff-logout'),
    path('staff-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('staff-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),

    path('center-details/<int:id>/', center_details, name='center-details'),


]

Diagnostic_Laboratory/medicine_tests/urls.py
from django.urls import path

from .views import (

    all_tests,
    test_details,

    test_order,
    order_details_info,

    test_categories,
    categorise_tests,

    staff_approved,
    staff_rejected,

    add_test_by_admin,
    add_category_by_admin,
    filtered_categories_by_admin,
    filtered_categories_for_staff,

    delete_test,
    edit_test,

    edit_category,
    delete_category,

    all_tests_list_for_staff,
    added_tests_list_for_staff_admin,

    confirm_payment_message,

    came_for_test,

    total_test_count_center_staff,

)


app_name = 'medicine_tests'


urlpatterns = [

    path('all-medicine_tests/', all_tests, name='all-medicine_tests'),

    path('categories/', test_categories, name='categories'),

    path('categorise-medicine_tests/<int:id>/', categorise_tests, name='categorise-medicine_tests'),

    path('test-details/<int:id>/', test_details, name='test-details'),

    path('order/<int:id>/', test_order, name='order'),

    path('order-details/<int:id>/', order_details_info, name='order-details'),

    path('staff-approved/<int:id>/<username>/', staff_approved, name='staff-approved'),

    path('staff-rejected/<int:id>/<username>/', staff_rejected, name='staff-rejected'),

    path('add-test/<username>/', add_test_by_admin, name='add-test'),

    path('add-category/<username>/', add_category_by_admin, name='add-category'),

    path('filtered-categories-by-admin/<username>/', filtered_categories_by_admin, name='filtered-categories-by-admin'),

    path('filtered-categories-for-staff/<username>/', filtered_categories_for_staff, name='filtered-categories-for-staff'),

    path('all-medicine_tests-list-staff/<username>/', all_tests_list_for_staff, name='all-medicine_tests-list-staff'),

    path('added-medicine_tests-list-staff-admin/<username>/', added_tests_list_for_staff_admin, name='added-medicine_tests-list-staff-admin'),

    path('delete-test/<int:id>/<username>/', delete_test, name='delete_test'),

    path('delete-category/<int:id>/<username>/', delete_category, name='delete-category'),

    path('edit-test/<int:id>/<username>/', edit_test, name='edit-test'),

    path('edit-category/<int:id>/<username>/', edit_category, name='edit-category'),

    path('confirm-payment-message/<int:id>/', confirm_payment_message, name='confirm-payment-message'),

    path('staff-confirm-payment-message/<int:id>/<username>/', confirm_payment_message, name='staff-confirm-payment-message'),

    path('came-for-test/<int:id>/<username>/', came_for_test, name='came-for-test'),

    path('total-test-count-center-staff/<int:id>/', total_test_count_center_staff, name='total-test-count-center-staff'),


]

Diagnostic_Laboratory/report_processing/urls.py
from django.urls import path

from .views import all_reports, single_report_details, complete_due_payment


app_name = 'report_processing'

urlpatterns = [

    path('all-reports/', all_reports, name='all-reports'),

    path('single-report-details/<int:id>/', single_report_details, name='single-report-details'),

    path('complete-due-payment/<int:id>/<int:report_id>/', complete_due_payment, name='complete-due-payment'),

]

Diagnostic_Laboratory/report_processing/models.py
from django.db import models

from medicine_tests.models import TestOrder


class PaymentValidation(models.Model):

    approved_order = models.ForeignKey(TestOrder, on_delete=models.SET_NULL, null=True, blank=True)

    upload_report = models.FileField(upload_to='reports_PDF', null=True, blank=True)

    send_message = models.CharField(max_length=250, null=True, blank=True)

    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

Diagnostic_Laboratory/report_processing/forms.py
from django import forms
from django.forms import TextInput, FileInput

from .models import PaymentValidation


class PaymentValidationForm(forms.ModelForm):
    class Meta:
        model = PaymentValidation

        fields = '__all__'
        exclude = ['approved_order', ]

        widgets = {
            'upload_report': FileInput(attrs={'class': 'form-control'}),
            'send_message': TextInput(attrs={'class': 'form-control'}),
        }

Diagnostic_Laboratory/report_processing/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from custom_users.models import Profile
from medicine_tests.models import Test, TestOrder

from .models import PaymentValidation
from .forms import PaymentValidationForm

########################################################################################################################


def all_reports(request):
    all_reports_query = PaymentValidation.objects.all()
    paginator = Paginator(all_reports_query, 5)
    page = request.GET.get('page')
    all_reports_paginator = paginator.get_page(page)
    template = 'report_processing/all_reports.html'
    context = {'all_reports_query': all_reports_paginator}

    return render(request, template, context)

########################################################################################################################

def single_report_details(request, id=None):
    report_details = PaymentValidation.objects.get(id=id)
    total_price = int(report_details.approved_order.test_info.price - report_details.approved_order.test_info.discount)
    due_price = int(
        (report_details.approved_order.test_info.price - report_details.approved_order.test_info.discount) / 2)

    template = 'report_processing/single_report_details.html'
    context = {
        'report_details': report_details,
        'total_price': total_price,
        'due_price': due_price,
    }

    return render(request, template, context)

########################################################################################################################


def complete_due_payment(request, id=None, report_id=None):
    existing_order = TestOrder.objects.get(id=id)
    existing_order.payment_type ='Full Payment'
    existing_order.validation = False
    existing_order.save()

    report_details = PaymentValidation.objects.get(id=report_id)

    total_price = int(report_details.approved_order.test_info.price - report_details.approved_order.test_info.discount)

    due_price = int(
        (report_details.approved_order.test_info.price - report_details.approved_order.test_info.discount) / 2)

    template = 'report_processing/single_report_details.html'

    context = {
        'report_details': report_details,
        'total_price': total_price,
        'due_price': due_price,
    }

    return render(request, template, context)

Diagnostic_Laboratory/templates/report_processing/all_reports.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Все отчёты | Диагностика</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <style>
        p {
            margin-bottom: 0;
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-warning" href="#"><b>Диагностика</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

{#
                    <li class="nav-item">
                        <!-- <button type="submit"> -->
                        <a class="nav-link text-white" href="{% url 'medicine_tests:all-medicine_tests-list-staff-admin' %}">Недавно
                            Добавленные
                            Анализы</a>
                        <!-- </button> -->
                    </li>

{#
                </ul>
            </div>
        </div>
    </nav>


    <table class="table table-striped table-bordered table-hover mb-4">
        <thead>
        <tr class="bg-primary text-white">
            <th colspan="6"> Все заверенные результаты </th>
        </tr>
        <tr style="background-color: forestgreen">
            <th>SL NO.</th>
            <th> Название анализа </th>
            <th> Время подтверждения </th>
            <th> Результаты </th>
            <th> Сообщения </th>

        </tr>
        </thead>

        <tbody>

        {% for report in all_reports_query %}

            <tr>
                <td> {{ forloop.counter }} </td>
                <td><a href="{% url 'report_processing:single-report-details' report.id %}"><b style="color: green">
                    {{ report.approved_order.test_info.test_name }}
                </b></a></td>
                <td><b style="color: deeppink">{{ report.datetime }}</b></td>
                <td><a href="/media/reports_PDF/report_demo.pdf"><b style="color: blue">{{ report.upload_report }}</b></a></td>
                <td><b style="color: blue">{{ report.send_message }}</b></td>
            </tr>

        {% endfor %}

        </tbody>
    </table>

    <!-- All reports Paginator -->
    <ul class="pagination">
        <li class="page-item">

            {% if all_reports_query.has_previous %}
                <a class="page-link" href="?page={{ all_reports_query.previous_page_number }}"
                   aria-label="Previous">
                    <span aria-hidden="false">&laquo;</span>
                </a>
            {% endif %}

        </li>
        <li class="page-item">
            <a class="page-link" href="#">Страница {{ all_reports_query.number }} of
                {{ all_reports_query.paginator.num_pages }}.</a>
        </li>
        <li class="page-item">

            {% if all_reports_query.has_next %}

                <a class="page-link" href="?page={{ all_reports_query.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
        </li>
    </ul>
    <!-- All reports Paginator -->


    <br>
    <br>
    <div class="footer bg-dark text-white text-center py-2">
        <p class="mb-0"> &copy; Copyrights. All rights reserved. </p>
    </div>

</body>

</html>

Diagnostic_Laboratory/templates/report_processing/complete_due_payment.html
{% extends 'base.html' %}

{% block title %}Complete Due Payment Form | ODLRS{% endblock %}

{% block content %}
<div>
    <div class="row my-5">
        <div class="col-6 offset-3 text-cente">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Complete Due Payment</h3>
                </div>
                <div class="card-body">

{#                    <form action="{% url 'medicine_tests:order' test_id %}" method="post">#}
                    <form action="#" method="post">
                        {% csrf_token %}

                        {{ complete_due_payment_form.as_p }}
                        <br>
                        <button type="submit" class="btn btn-primary btn-sm">
                            PAYMENT
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Diagnostic_Laboratory/templates/report_processing/single_report_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Report Details | ODLRS</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body class="common-bg pt-0">
    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <div class="container my-5">
        <div class="single-reports card-width">
            <div class="card">
                <div class="card-header bg-dark text-white text-center
                        py-3">
                    <h3 class="mb-0">Completed Order Details</h3>
                </div>
                <div class="card-bottom-img"></div>

                <div class="card-body">
                    <!-- Flag -->
                    {% if report_details.approved_order.payment_type == 'Half Payment' %}
                    <div class="alert alert-danger">
                        <strong class="">Payment Due ₱{{ due_price }}</strong>
                        <!-- <a href="#" class="text-danger" data-dismiss="alert">&times;</a> -->
                    </div>
                    {% else %}
                    <div class="alert alert-success">
                        <strong>Full Payment Complete</strong>
                        <!-- <a href="#" class="text-succes float-right" data-dismiss="alert">&times;</a> -->
                    </div>
                    {% endif %}

                    <!-- Flag -->
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Name</p>
                                <p>
                                    {{ report_details.approved_order.client_info.user.customer_profile.profile_name }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Test Name</p>
                                <p>{{ report_details.approved_order.test_info.test_name }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Email</p>
                                <p>{{ report_details.approved_order.client_info.user.email }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Contact</p>
                                <p>{{ report_details.approved_order.client_info.user.customer_profile.contact_no }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Booked DateTime</p>
                                <p>
                                    {{ report_details.approved_order.booked_date }}
                                    ({{ report_details.approved_order.booked_time_slot }})
                                </p>
                            </div>
                        </div>

                        {% if report_details.approved_order.payment_type == 'Half Payment' %}

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-danger">
                                <p>Received Payment</p>
                                <p>{{ total_price }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-danger">
                                <p>Due</p>
                                <p>{{ due_price }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-danger">
                                <p>Payment Status</p>
                                <p>
                                    {{ report_details.approved_order.payment_type }}
                                    ({{ report_details.approved_order.payment_method}})
                                </p>
                            </div>
                        </div>
                        {% else %}

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Total Price</p>
                                <p> ₱{{ total_price }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Received Payment</p>
                                <p> ₱{{ total_price }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Payment Status</p>
                                <p>
                                    {{ report_details.approved_order.payment_type }}
                                    ({{ report_details.approved_order.payment_method}})
                                </p>
                            </div>
                        </div>
                        {% endif %}

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Validation DateTime</p>
                                <p>
                                    {{ report_details.datetime }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group">
                                <p class="">Download Report</p>
                                <a href="/media/reports_PDF/report_demo.pdf"
                                    class="text-danger">{{ report_details.upload_report }}</a>
                            </div>
                        </div>

                        <div class="col">
                            <div class="row mt-2">
                                {% if request.user.is_authenticated %}
                                <div class="col-xs-12 col-sm-6 col-md-6">
                                    <a href="{% url 'home' %}" class="btn btn-warning w-100">Back to Home
                                    </a>
                                </div>
                                    {% if report_details.approved_order.payment_type == 'Half Payment' %}
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                    <a class="btn btn-success w-100"
                                        href="{% url 'report_processing:complete-due-payment' report_details.approved_order.id report_details.id %}">
                                        CompletePayment
                                    </a>
                                    </div>
                                    {% endif %}
                                {% endif %}
{#                                {% if report_details.approved_order.payment_type == 'Half Payment' %}#}
{#                                <div class="col-xs-12 col-sm-6 col-md-6">#}
{#                                    <a class="btn btn-success w-100"#}
{#                                        href="{% url 'report_processing:complete-due-payment' report_details.approved_order.id report_details.id %}">#}
{#                                        CompletePayment#}
{#                                    </a>#}
{#                                </div>#}
{#                                {% endif %}#}
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    </div>

    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>